#!/usr/bin/env bash
# auto-pr.sh — push the current branch and open a PR via the `gh` CLI.
#
# Generated by repo-builder --automation. Designed for use by:
#   - DSH agent subagents finishing a milestone
#   - local developers wrapping up a feature branch
#   - the rollback workflow's "re-open PR for the revert" path
#
# Usage:
#   ./scripts/auto-pr.sh                 # auto-generate title from commits
#   ./scripts/auto-pr.sh "feat: foo"     # explicit title
#   ./scripts/auto-pr.sh --draft         # open as draft
#
# Requires: gh CLI authenticated (`gh auth login`).

set -euo pipefail

if ! command -v gh >/dev/null 2>&1; then
  echo "ERROR: 'gh' CLI not found. Install from https://cli.github.com/" >&2
  exit 1
fi

# ── Determine current branch ─────────────────────────────────────────────
BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD)
if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "master" ]; then
  echo "ERROR: refusing to open a PR from $BRANCH (the default branch)" >&2
  echo "       Create a feature branch first: git checkout -b feat/<name>" >&2
  exit 2
fi

# ── Parse args ───────────────────────────────────────────────────────────
DRAFT=""
TITLE="${1:-}"
shift || true
while [ $# -gt 0 ]; do
  case "$1" in
    --draft) DRAFT="--draft" ;;
    --base)  shift; BASE="$1" ;;
    --body)  shift; BODY_FILE="$1" ;;
    *) echo "unknown arg: $1" >&2; exit 3 ;;
  esac
  shift
done

# Default title: last commit subject
if [ -z "$TITLE" ]; then
  TITLE=$(git log -1 --pretty=%s)
fi

# Default base: repo default branch (from origin/HEAD)
if [ -z "${BASE:-}" ]; then
  BASE=$(git remote show origin 2>/dev/null | awk '/HEAD branch/ {print $NF}')
  BASE="${BASE:-main}"
fi

# Default body: commits on this branch since divergence from base
if [ -z "${BODY_FILE:-}" ]; then
  BODY_FILE=$(mktemp -t auto-pr-body.XXXXXX)
  trap 'rm -f "$BODY_FILE"' EXIT
  {
    echo "## Summary"
    echo
    echo "Auto-generated by \`repo-builder --automation\`."
    echo
    echo "## Commits"
    echo
    git log --pretty=format:'- %s' "origin/${BASE}..HEAD" 2>/dev/null \
      || git log --pretty=format:'- %s' -n 10
    echo
    echo
    echo "## Verify"
    echo
    echo "CI will run \`npm test\` + \`npm run build\`."
  } > "$BODY_FILE"
fi

# ── Push + open PR ───────────────────────────────────────────────────────
echo "→ Pushing $BRANCH to origin..."
git push -u origin "$BRANCH"

echo "→ Opening PR: $TITLE"
gh pr create \
  --base "$BASE" \
  --head "$BRANCH" \
  --title "$TITLE" \
  --body-file "$BODY_FILE" \
  $DRAFT

echo "✓ Done."
