#!/usr/bin/env bash
# rollback.sh — manual rollback helper.
#
# Generated by repo-builder --automation. Used by:
#   - humans when prod is on fire and the GitHub Action is too slow
#   - the rollback workflow when triggered automatically
#
# Usage:
#   ./scripts/rollback.sh                       # roll back to previous release tag
#   ./scripts/rollback.sh <sha-or-tag>          # roll back to specific ref
#   ./scripts/rollback.sh --dry-run             # show what would happen, do nothing
#
# Requires: gh CLI authenticated with repo:write.

set -euo pipefail

# ── Defaults ─────────────────────────────────────────────────────────────
TARGET=""
DRY_RUN=""
PROD_BRANCH="${PROD_BRANCH:-main}"

# ── Parse args ───────────────────────────────────────────────────────────
while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN="--dry-run" ;;
    --prod-branch) shift; PROD_BRANCH="$1" ;;
    -h|--help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *)
      TARGET="$1"
      ;;
  esac
  shift
done

# ── Pre-flight ───────────────────────────────────────────────────────────
if ! command -v gh >/dev/null 2>&1; then
  echo "ERROR: 'gh' CLI required. Install from https://cli.github.com/" >&2
  exit 1
fi

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "ERROR: not inside a git repo" >&2
  exit 2
fi

if [ "$(git symbolic-ref --short HEAD)" != "$PROD_BRANCH" ]; then
  echo "ERROR: must be on $PROD_BRANCH branch to roll back (currently on $(git symbolic-ref --short HEAD))" >&2
  echo "       Switch with: git checkout $PROD_BRANCH" >&2
  exit 3
fi

# ── Determine target if not given ────────────────────────────────────────
if [ -z "$TARGET" ]; then
  echo "▶ Finding previous release tag..."
  TARGET=$(gh release list --limit 5 --json tagName --jq '.[].tagName' 2>/dev/null \
            | head -1 || true)
  if [ -z "$TARGET" ]; then
    # Fall back to previous commit
    TARGET="HEAD~1"
    echo "  no release tag found; using $TARGET"
  else
    echo "  found: $TARGET"
  fi
fi

# ── Confirm ──────────────────────────────────────────────────────────────
echo
echo "About to roll back smart-dining on $PROD_BRANCH to: $TARGET"
if [ -n "$DRY_RUN" ]; then
  echo "(dry-run mode — no changes will be made)"
fi
echo
read -p "Continue? [y/N] " -n 1 -r
echo
if [[ ! "$REPLY" =~ ^[Yy]$ ]]; then
  echo "Aborted."
  exit 0
fi

# ── Execute ──────────────────────────────────────────────────────────────
if [ -n "$DRY_RUN" ]; then
  echo "DRY-RUN: would run: git revert --no-edit HEAD && git push origin $PROD_BRANCH"
  echo "DRY-RUN: target = $TARGET"
  exit 0
fi

git config user.name "rollback-bot"
git config user.email "rollback-bot@users.noreply.github.com"

echo "▶ Reverting HEAD on $PROD_BRANCH..."
git revert --no-edit HEAD

echo "▶ Pushing revert..."
git push origin "$PROD_BRANCH"

echo
echo "✓ Rollback pushed. The deploy-prod workflow will fire automatically."
echo "  Watch: $0 (open the GitHub Actions tab)"
echo
echo "Optional followups:"
echo "  - Tag the new HEAD as a release:    gh release create \"v\$(date -u +%Y%m%d)\""
echo "  - Announce in Slack:                (your team's runbook)"
echo "  - File a post-mortem:               (your team's runbook)"
